[package]
name = "vcpu"
version = "0.1.0"
edition = "2021"

[dependencies]
enumflags2 = "0.7"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
vcpu-derive = { version = "0.1", path = "vcpu_derive" }

[workspace]
resolver = "2"
members = ["vcpu_derive"]